CREATE TABLE practice_portfolios (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    mode VARCHAR(16) NOT NULL,
    initial_cash DECIMAL(28,10) NOT NULL,
    created_at VARCHAR(40) NOT NULL
);
CREATE TABLE paper_trades (
    sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id VARCHAR(36) NOT NULL REFERENCES practice_portfolios(id),
    request_id VARCHAR(36) NOT NULL,
    ticker VARCHAR(16) NOT NULL,
    side VARCHAR(4) NOT NULL,
    quantity DECIMAL(20,6) NOT NULL,
    price DECIMAL(20,4) NOT NULL,
    fee DECIMAL(20,2) NOT NULL,
    recorded_at VARCHAR(40) NOT NULL,
    UNIQUE(portfolio_id, request_id)
);
CREATE INDEX trades_by_portfolio ON paper_trades(portfolio_id, sequence_id);
