CREATE TABLE portfolio_events (
    sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id VARCHAR(36) NOT NULL REFERENCES practice_portfolios(id),
    request_id VARCHAR(36) NOT NULL,
    kind VARCHAR(16) NOT NULL,
    ticker VARCHAR(16) NOT NULL,
    event_value DECIMAL(20,4),
    denominator DECIMAL(20,0),
    recorded_at VARCHAR(40) NOT NULL,
    UNIQUE(portfolio_id, request_id)
);
INSERT INTO portfolio_events(portfolio_id, request_id, kind, ticker, recorded_at)
    SELECT portfolio_id, request_id, 'TRADE', ticker, recorded_at
    FROM paper_trades ORDER BY sequence_id;
CREATE INDEX events_by_portfolio ON portfolio_events(portfolio_id, sequence_id);
