CREATE TABLE research_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(16) NOT NULL,
    entry_id VARCHAR(36) NOT NULL,
    action VARCHAR(16) NOT NULL,
    recorded_at VARCHAR(40) NOT NULL,
    status VARCHAR(16) NOT NULL,
    thesis VARCHAR(2000) NOT NULL,
    risks VARCHAR(1000) NOT NULL,
    review_date VARCHAR(10),
    version BIGINT NOT NULL,
    created_at VARCHAR(40) NOT NULL,
    updated_at VARCHAR(40) NOT NULL,
    research_checks VARCHAR(500) NOT NULL,
    UNIQUE (entry_id, version, action)
);
CREATE INDEX research_revisions_ticker_id ON research_revisions(ticker, id);
