import { money } from './api';
import type { PortfolioMarks } from './types';

export type StressResult = { baseline: PortfolioMarks; assumptions: { defaultShock: number; sectorShocks: Record<string, number> };
  holdings: { baseline: PortfolioMarks['holdings'][number]; sector: string; shock: number; stressedValue: number | null; change: number | null }[];
  stressedPricedHoldingsValue: number; stressedTotalValue: number | null; change: number | null; relativeChange: number | null };

const dollars = (value: number | null) => value === null ? 'Unavailable' : money(value, false);
export default function PortfolioStressResult({ result, historical = false }: { result: StressResult; historical?: boolean }) {
  return <div aria-live="polite">
      <p className="notice warning">{result.baseline.dataMode === 'example' ? 'Invented example closes.' : 'Stored market closes.'} {result.baseline.pricedPositions} of {result.baseline.totalPositions} holdings priced. Baseline evaluated {new Date(result.baseline.evaluatedAt).toLocaleString()}. {historical ? 'This is a saved snapshot, not the current portfolio.' : 'No trades or cash entries were changed.'}</p>
      {!result.baseline.complete && <p className="notice warning">Full portfolio totals and changes are unavailable. Subtotals exclude unpriced holdings.</p>}
      <div className="result-summary"><div><span>Baseline · cash + holdings</span><strong>{dollars(result.baseline.totalValue)}</strong></div><div><span>Stressed · cash + holdings</span><strong data-testid={historical ? "saved-stress-total" : "stress-total"}>{dollars(result.stressedTotalValue)}</strong></div><div><span>Hypothetical value change</span><strong data-testid={historical ? "saved-stress-change" : "stress-change"}>{dollars(result.change)}</strong></div><div><span>Change / baseline value</span><strong>{result.relativeChange === null ? 'Unavailable' : `${(result.relativeChange * 100).toFixed(2)}%`}</strong></div></div>
      <p className="muted small">Cash held fixed: {money(result.baseline.cash, false)}. Priced holdings subtotal: {money(result.baseline.pricedHoldingsValue, false)} → {money(result.stressedPricedHoldingsValue, false)}.</p>
      <div className="table-scroll"><table><caption>Hypothetical holding values and baseline evidence</caption><thead><tr><th>Holding / sector</th><th>Price change</th><th>Baseline value</th><th>Stressed value</th><th>Value change</th><th>Baseline evidence</th></tr></thead><tbody>{result.holdings.map(row => <tr key={row.baseline.ticker}><th scope="row">{row.baseline.ticker}<small className="comparison-evidence">{row.sector}</small></th><td>{(row.shock * 100).toFixed(2)}%</td><td>{dollars(row.baseline.value)}</td><td>{dollars(row.stressedValue)}</td><td>{dollars(row.change)}</td><td className="mark-evidence">{row.baseline.error || <>{row.baseline.priceDate} · {row.baseline.priceAgeDays} calendar days old<small className="comparison-evidence">{row.baseline.sourceUrl ? <a href={row.baseline.sourceUrl} target="_blank" rel="noreferrer">{row.baseline.source} ↗</a> : row.baseline.source}</small><small className="comparison-evidence">{row.baseline.retrievedAt ? `Imported ${new Date(row.baseline.retrievedAt).toLocaleString()}` : 'Fictional data · no market import'}</small></>}</td></tr>)}{!result.holdings.length && <tr><td colSpan={6}>Cash only. Price changes have no effect.</td></tr>}</tbody></table></div>
      <p className="muted small">I apply each shock once to the holding value, without changing share counts. This calculation excludes trading costs, taxes, liquidity, correlations, and currency changes. {historical ? 'This snapshot preserves the baseline used when saving. Load its assumptions and run again to evaluate current holdings.' : 'Each run reloads the current ledger and stored snapshots; it may use a newer baseline than the valuation above.'}</p>
    </div>;
}
